<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cities')->delete();
        
        \DB::table('cities')->insert(array (
            0 => 
            array (
                'id' => 1,
                'country_id' => 30,
                'name' => 'Barcelona',
                'cost' => 1915.0,
                'weather' => NULL,
                'longitude' => 41.3851,
                'latitude' => 2.1734,
                'housing' => 6.45,
                'cost_of_living' => 5.9399999999999995,
                'travel_connectivity' => 5.86,
                'commute' => 5.44,
                'safety' => 7.51,
                'business_freedom' => 7.12,
                'healthcare' => 8.42,
                'education' => 5.02,
                'economy' => 4.29,
                'environment_quality' => 3.88,
                'taxation' => 3.7800000000000002,
                'internet_access' => 5.9399999999999995,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:45',
            ),
            1 => 
            array (
                'id' => 2,
                'country_id' => 6,
                'name' => 'Moscow',
                'cost' => 1566.0,
                'weather' => NULL,
                'longitude' => 55.7558,
                'latitude' => 37.6173,
                'housing' => 6.58,
                'cost_of_living' => 7.84,
                'travel_connectivity' => 9.03,
                'commute' => 4.33,
                'safety' => 7.46,
                'business_freedom' => 5.39,
                'healthcare' => 4.72,
                'education' => 4.57,
                'economy' => 3.15,
                'environment_quality' => 5.45,
                'taxation' => 5.97,
                'internet_access' => 7.84,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:46',
            ),
            2 => 
            array (
                'id' => 3,
                'country_id' => 1,
                'name' => 'Wroclaw',
                'cost' => 1053.0,
                'weather' => NULL,
                'longitude' => 51.1079,
                'latitude' => 17.0385,
                'housing' => 8.43,
                'cost_of_living' => 8.42,
                'travel_connectivity' => 2.25,
                'commute' => 4.8100000000000005,
                'safety' => 7.89,
                'business_freedom' => 5.7,
                'healthcare' => 6.63,
                'education' => 4.16,
                'economy' => 4.76,
                'environment_quality' => 5.22,
                'taxation' => 5.0,
                'internet_access' => 8.42,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:47',
            ),
            3 => 
            array (
                'id' => 4,
                'country_id' => 11,
                'name' => 'Medellin',
                'cost' => 750.0,
                'weather' => NULL,
                'longitude' => 6.2442,
                'latitude' => 75.5812,
                'housing' => 9.54,
                'cost_of_living' => 9.52,
                'travel_connectivity' => 0.93,
                'commute' => 4.6899999999999995,
                'safety' => 7.51,
                'business_freedom' => 6.35,
                'healthcare' => 6.8100000000000005,
                'education' => 1.53,
                'economy' => 4.59,
                'environment_quality' => 5.95,
                'taxation' => 1.73,
                'internet_access' => 9.52,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:48',
            ),
            4 => 
            array (
                'id' => 5,
                'country_id' => 2,
                'name' => 'Las Vegas',
                'cost' => 1688.0,
                'weather' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'housing' => 6.75,
                'cost_of_living' => 5.48,
                'travel_connectivity' => 3.5300000000000002,
                'commute' => 4.89,
                'safety' => 2.36,
                'business_freedom' => 8.67,
                'healthcare' => 5.9399999999999995,
                'education' => 3.62,
                'economy' => 6.51,
                'environment_quality' => 5.77,
                'taxation' => 4.68,
                'internet_access' => 5.48,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:50',
            ),
            5 => 
            array (
                'id' => 6,
                'country_id' => 2,
                'name' => 'New York',
                'cost' => 4276.0,
                'weather' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'housing' => 1.0,
                'cost_of_living' => 2.34,
                'travel_connectivity' => 6.68,
                'commute' => 5.04,
                'safety' => 7.06,
                'business_freedom' => 8.67,
                'healthcare' => 6.07,
                'education' => 8.07,
                'economy' => 6.51,
                'environment_quality' => 5.35,
                'taxation' => 3.8,
                'internet_access' => 2.34,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:51',
            ),
            6 => 
            array (
                'id' => 7,
                'country_id' => 2,
                'name' => 'San Francisco Bay Area',
                'cost' => 4419.0,
                'weather' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'housing' => 1.0,
                'cost_of_living' => 2.82,
                'travel_connectivity' => 3.67,
                'commute' => 4.74,
                'safety' => 5.76,
                'business_freedom' => 8.67,
                'healthcare' => 6.45,
                'education' => 8.62,
                'economy' => 6.51,
                'environment_quality' => 6.55,
                'taxation' => 4.38,
                'internet_access' => 2.82,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:52',
            ),
            7 => 
            array (
                'id' => 8,
                'country_id' => 14,
                'name' => 'Rio de Janeiro',
                'cost' => 1223.0,
                'weather' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'housing' => 7.98,
                'cost_of_living' => 7.02,
                'travel_connectivity' => 1.49,
                'commute' => 4.15,
                'safety' => 5.3,
                'business_freedom' => 4.04,
                'healthcare' => 4.87,
                'education' => 1.02,
                'economy' => 2.19,
                'environment_quality' => 3.4699999999999998,
                'taxation' => 2.76,
                'internet_access' => 7.02,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:53',
            ),
            8 => 
            array (
                'id' => 9,
                'country_id' => 14,
                'name' => 'Sao Paulo',
                'cost' => 1231.0,
                'weather' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'housing' => 8.09,
                'cost_of_living' => 7.11,
                'travel_connectivity' => 2.27,
                'commute' => 4.3,
                'safety' => 5.42,
                'business_freedom' => 2.7800000000000002,
                'healthcare' => 5.39,
                'education' => 1.1,
                'economy' => 2.19,
                'environment_quality' => 2.37,
                'taxation' => 2.77,
                'internet_access' => 7.11,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:54',
            ),
            9 => 
            array (
                'id' => 10,
                'country_id' => 11,
                'name' => 'Bogota',
                'cost' => 886.0,
                'weather' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'housing' => 9.09,
                'cost_of_living' => 9.21,
                'travel_connectivity' => 1.8900000000000001,
                'commute' => 4.9,
                'safety' => 6.26,
                'business_freedom' => 6.35,
                'healthcare' => 6.39,
                'education' => 1.53,
                'economy' => 4.59,
                'environment_quality' => 4.21,
                'taxation' => 1.73,
                'internet_access' => 9.21,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:55',
            ),
            10 => 
            array (
                'id' => 11,
                'country_id' => 31,
                'name' => 'Buenos Aires',
                'cost' => 1076.0,
                'weather' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'housing' => 8.68,
                'cost_of_living' => 7.08,
                'travel_connectivity' => 3.92,
                'commute' => 4.62,
                'safety' => 6.14,
                'business_freedom' => 4.05,
                'healthcare' => 7.01,
                'education' => 1.42,
                'economy' => 2.88,
                'environment_quality' => 4.6,
                'taxation' => 1.44,
                'internet_access' => 7.08,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:57',
            ),
            11 => 
            array (
                'id' => 12,
                'country_id' => 15,
                'name' => 'Lima',
                'cost' => 1019.0,
                'weather' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'housing' => 8.63,
                'cost_of_living' => 8.43,
                'travel_connectivity' => 2.01,
                'commute' => 4.76,
                'safety' => 5.43,
                'business_freedom' => 5.0,
                'healthcare' => 5.91,
                'education' => 0.5,
                'economy' => 3.16,
                'environment_quality' => 2.86,
                'taxation' => 6.46,
                'internet_access' => 8.43,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:58',
            ),
            12 => 
            array (
                'id' => 13,
                'country_id' => 8,
                'name' => 'Tokyo',
                'cost' => 2248.0,
                'weather' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'housing' => 5.48,
                'cost_of_living' => 3.23,
                'travel_connectivity' => 8.15,
                'commute' => 5.46,
                'safety' => 9.97,
                'business_freedom' => 8.38,
                'healthcare' => 8.88,
                'education' => 6.97,
                'economy' => 3.7199999999999998,
                'environment_quality' => 6.08,
                'taxation' => 5.99,
                'internet_access' => 3.23,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:31:59',
            ),
            13 => 
            array (
                'id' => 14,
                'country_id' => 3,
                'name' => 'Bangkok',
                'cost' => 1338.0,
                'weather' => NULL,
                'longitude' => NULL,
                'latitude' => NULL,
                'housing' => 7.57,
                'cost_of_living' => 7.22,
                'travel_connectivity' => 4.05,
                'commute' => 3.96,
                'safety' => 7.19,
                'business_freedom' => 5.6,
                'healthcare' => 7.24,
                'education' => 1.69,
                'economy' => 2.39,
                'environment_quality' => 3.51,
                'taxation' => 6.73,
                'internet_access' => 7.22,
                'created_at' => NULL,
                'updated_at' => '2018-02-20 21:32:00',
            ),
        ));
        
        
    }
}